/* eslint-disable no-unused-vars */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 house.gltf --transform 
Files: house.gltf [3.48MB] > C:\Users\raj25\OneDrive\Desktop\modern\house-transformed.glb [270.68KB] (92%)
Author: qurbanova.irade (https://sketchfab.com/qurbanova.irade)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/modern-9da074958dba46e88d36c6f0a6c01f62
Title: modern
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/house-transformed.glb')
  return (
    <group {...props}  dispose={null}>
      <lineSegments geometry={nodes.Material28.geometry} material={materials.PaletteMaterial001} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material22.geometry} material={materials.PaletteMaterial001} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material3.geometry} material={materials.Material3} rotation={[-Math.PI /2, 0, 0]} />
      <mesh geometry={nodes.Material8.geometry} material={materials.Material8} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material15.geometry} material={materials.Material15} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material6.geometry} material={materials.Material6} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material10.geometry} material={materials.Material10} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material9.geometry} material={materials.Material9} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material4.geometry} material={materials.Material4} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material23.geometry} material={materials.Material23} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material24.geometry} material={materials.PaletteMaterial002} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material14.geometry} material={materials.Material14} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material25.geometry} material={materials.Material25} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material26.geometry} material={materials.Material26} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material27.geometry} material={materials.Material27} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material11.geometry} material={materials.Material11} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/house-transformed.glb')
